-- MySQL Script generated by MySQL Workbench
-- Sun Jun 10 15:16:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yisong
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yisong
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yisong` DEFAULT CHARACTER SET utf8mb4 ;
USE `yisong` ;

-- -----------------------------------------------------
-- Table `yisong`.`ys_admin_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_admin_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_group_id` VARCHAR(40) NOT NULL,
  `rule` VARCHAR(150) NULL,
  `group_name` VARCHAR(45) NOT NULL,
  `group_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admin_group_id_UNIQUE` (`admin_group_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '权限组';


-- -----------------------------------------------------
-- Table `yisong`.`ys_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '用户状态，1正常用户，2冻结用户',
  `type` INT NOT NULL DEFAULT 3 COMMENT '用户类型，1：品牌商，2：代理商，3：门店',
  `admin_group_id` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_ys_admin_ys_admin_group1_idx` (`admin_group_id` ASC),
  CONSTRAINT `fk_ys_admin_ys_admin_group1`
    FOREIGN KEY (`admin_group_id`)
    REFERENCES `yisong`.`ys_admin_group` (`admin_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '后台管理员用户';


-- -----------------------------------------------------
-- Table `yisong`.`ys_agent_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_agent_level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agent_level_id` VARCHAR(40) NOT NULL,
  `agent_level_name` VARCHAR(45) NOT NULL,
  `parent_id` INT NOT NULL,
  `rank` VARCHAR(10) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ys_agent_level_ys_agent_level1_idx` (`parent_id` ASC),
  UNIQUE INDEX `agent_level_id_UNIQUE` (`agent_level_id` ASC),
  CONSTRAINT `fk_ys_agent_level_ys_agent_level1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `yisong`.`ys_agent_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '代理商等级';


-- -----------------------------------------------------
-- Table `yisong`.`ys_agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_agent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agent_id` VARCHAR(40) NOT NULL,
  `agent_name` VARCHAR(45) NOT NULL,
  `agent_level_id` VARCHAR(40) NOT NULL,
  `contact_name` VARCHAR(10) NOT NULL COMMENT '代理商联系人姓名',
  `contect_phone` VARCHAR(20) NOT NULL COMMENT '代理商联系电话',
  `area` VARCHAR(45) NOT NULL COMMENT '区域',
  `status` INT NOT NULL DEFAULT 1 COMMENT '代理商状态，1：正常，2：冻结',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `begin_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `end_time` TIMESTAMP NULL,
  `business_lice` VARCHAR(100) NULL COMMENT '营业执照地址url',
  `idcard_up` VARCHAR(100) NULL COMMENT '身份证地址url',
  `idcard_down` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `agent_id_UNIQUE` (`agent_id` ASC),
  INDEX `fk_ys_agent_ys_agent_level1_idx` (`agent_level_id` ASC),
  CONSTRAINT `fk_ys_agent_ys_agent_level1`
    FOREIGN KEY (`agent_level_id`)
    REFERENCES `yisong`.`ys_agent_level` (`agent_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '代理商';


-- -----------------------------------------------------
-- Table `yisong`.`ys_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `store_id` VARCHAR(40) CHARACTER SET 'utf8mb4' NOT NULL,
  `agent_id` VARCHAR(40) NOT NULL,
  `store_name` VARCHAR(45) NOT NULL,
  `localtion` VARCHAR(45) NOT NULL COMMENT '地理位置经纬度',
  `path` DOUBLE(16,2) NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '门店状态，1：正常，2：闭店',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '门店创建时间，自动填充为添加门店时的时间戳',
  `begin_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `end_time` TIMESTAMP NULL,
  `contact_name` VARCHAR(10) NOT NULL,
  `contact_phone` VARCHAR(20) NOT NULL,
  `address` VARCHAR(100) NOT NULL COMMENT '地理位置信息',
  `area` VARCHAR(100) NOT NULL COMMENT '区域',
  `business_lice` VARCHAR(100) NULL,
  `idcard` VARCHAR(100) NULL,
  `send_money` DOUBLE(16,2) NULL,
  `open_day` VARCHAR(7) NOT NULL,
  `open_begin_time` INT NOT NULL,
  `open_end_time` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC),
  INDEX `fk_ys_store_ys_agent_idx` (`agent_id` ASC),
  CONSTRAINT `fk_ys_store_ys_agent`
    FOREIGN KEY (`agent_id`)
    REFERENCES `yisong`.`ys_agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '门店';


-- -----------------------------------------------------
-- Table `yisong`.`ys_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_brand` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(45) NOT NULL,
  `brand_url` VARCHAR(45) NULL,
  `brand_logo` VARCHAR(100) NULL COMMENT '品牌logo url',
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '品牌商';


-- -----------------------------------------------------
-- Table `yisong`.`ys_goods_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_goods_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` VARCHAR(40) NOT NULL,
  `category_name` VARCHAR(20) NOT NULL,
  `parent_id` VARCHAR(40) NOT NULL,
  `rank` VARCHAR(10) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `goods_category_id_UNIQUE` (`category_id` ASC),
  INDEX `fk_ys_goods_category_ys_goods_category1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_ys_goods_category_ys_goods_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `yisong`.`ys_goods_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '商品分类表';


-- -----------------------------------------------------
-- Table `yisong`.`ys_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `goods_id` VARCHAR(40) NOT NULL,
  `category_id` VARCHAR(40) NOT NULL,
  `goods_name` VARCHAR(45) NOT NULL,
  `unit` VARCHAR(10) NOT NULL COMMENT '单位',
  `keyword` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `cost_price` DOUBLE(16,2) NULL COMMENT '成本价',
  `sale_price` DOUBLE(16,2) NOT NULL COMMENT '销售价',
  `market_price` DOUBLE(16,2) NULL COMMENT '市场价',
  `stock` DOUBLE(16,2) NULL COMMENT '库存',
  `low_stock` DOUBLE(16,2) NULL COMMENT '库存预警',
  `publish` INT NOT NULL DEFAULT 2 COMMENT '是否发布，1：发布，2：不发布',
  `picture` VARCHAR(100) NULL COMMENT '图片url',
  PRIMARY KEY (`id`),
  INDEX `fk_ys_goods_ys_goods_category1_idx` (`category_id` ASC),
  UNIQUE INDEX `goods_id_UNIQUE` (`goods_id` ASC),
  CONSTRAINT `fk_ys_goods_ys_goods_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `yisong`.`ys_goods_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '商品表';


-- -----------------------------------------------------
-- Table `yisong`.`ys_goods_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_goods_discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discount_id` VARCHAR(40) NOT NULL,
  `goods_id` VARCHAR(40) NOT NULL,
  `discount` DOUBLE(16,2) NOT NULL,
  `begin_time` TIMESTAMP NULL,
  `end_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `discount_id_UNIQUE` (`discount_id` ASC),
  INDEX `fk_ys_goods_discount_ys_goods1_idx` (`goods_id` ASC),
  CONSTRAINT `fk_ys_goods_discount_ys_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `yisong`.`ys_goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '折扣';


-- -----------------------------------------------------
-- Table `yisong`.`ys_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(40) CHARACTER SET 'utf8mb4' NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `phone` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NULL,
  `last_login_time` TIMESTAMP NULL,
  `last_login_ip` VARCHAR(35) NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `score` INT NOT NULL DEFAULT 0 COMMENT '积分',
  `status` INT NOT NULL DEFAULT 1 COMMENT '状态，1：正常，2：冻结',
  `wallet` DOUBLE(16,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `yisong`.`ys_wx_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_wx_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `openid` VARCHAR(30) NOT NULL,
  `nickname` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL,
  `sex` INT NULL COMMENT '1时是男性，2时是女性，0时是未知',
  `language` VARCHAR(20) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `headimgurl` VARCHAR(300) NULL,
  `unionid` VARCHAR(45) NULL,
  `wx_appid` VARCHAR(45) NULL,
  `user_id` VARCHAR(40) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `openid_UNIQUE` (`openid` ASC),
  INDEX `fk_ys_wx_user_ys_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ys_wx_user_ys_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yisong`.`ys_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户微信信息';


-- -----------------------------------------------------
-- Table `yisong`.`ys_user_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_user_level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level_begin_score` INT NOT NULL,
  `level_end_score` INT NOT NULL,
  `level_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `yisong`.`ys_store_close_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_store_close_time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `begin_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `end_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `store_id` VARCHAR(40) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ys_store_close_time_ys_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_ys_store_close_time_ys_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `yisong`.`ys_store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '闭店时间';


-- -----------------------------------------------------
-- Table `yisong`.`ys_wx_store_slide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_wx_store_slide` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slide_id` VARCHAR(40) NOT NULL,
  `slide_url` VARCHAR(300) NOT NULL,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ys_store_id` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wx_store_id_UNIQUE` (`slide_id` ASC),
  INDEX `fk_ys_wx_store_slide_ys_store1_idx` (`ys_store_id` ASC),
  CONSTRAINT `fk_ys_wx_store_slide_ys_store1`
    FOREIGN KEY (`ys_store_id`)
    REFERENCES `yisong`.`ys_store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '微信端门店轮播图';


-- -----------------------------------------------------
-- Table `yisong`.`ys_store_notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_store_notice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notice_id` VARCHAR(40) NOT NULL,
  `store_id` VARCHAR(40) NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `notice_id_UNIQUE` (`notice_id` ASC),
  INDEX `fk_ys_store_notice_ys_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_ys_store_notice_ys_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `yisong`.`ys_store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '门店公告';


-- -----------------------------------------------------
-- Table `yisong`.`ys_store_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_store_menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `menu_id` VARCHAR(40) NOT NULL,
  `menu_name` VARCHAR(45) NOT NULL,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `store_id` VARCHAR(30) NOT NULL,
  `goods_id` VARCHAR(45) NOT NULL COMMENT '商品id，id之间用,分割',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menu_id_UNIQUE` (`menu_id` ASC),
  INDEX `fk_ys_store_menu_ys_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_ys_store_menu_ys_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `yisong`.`ys_store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '门店商品栏';


-- -----------------------------------------------------
-- Table `yisong`.`ys_store_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_store_goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `goods_id` VARCHAR(30) NOT NULL,
  `publish` INT NOT NULL DEFAULT 2 COMMENT '是否发布，1：发布，2：不发布',
  `stock` DOUBLE(16,2) NULL,
  `store_id` VARCHAR(30) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_ys_store_goods_ys_goods1_idx` (`goods_id` ASC),
  INDEX `fk_ys_store_goods_ys_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_ys_store_goods_ys_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `yisong`.`ys_goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ys_store_goods_ys_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `yisong`.`ys_store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '门店商品表';


-- -----------------------------------------------------
-- Table `yisong`.`ys_print_machine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_print_machine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `print_id` VARCHAR(45) NOT NULL,
  `machine_code` VARCHAR(45) NOT NULL COMMENT '打印机编号',
  `client_id` VARCHAR(45) NULL COMMENT '应用id',
  `client_secret` VARCHAR(45) NULL COMMENT '应用secret',
  `refresh_token` VARCHAR(45) NULL,
  `access_token` VARCHAR(45) NULL,
  `expires_in` INT NULL,
  `update_time` TIMESTAMP NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1:启用，2：禁用',
  `store_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `print_id_UNIQUE` (`print_id` ASC),
  INDEX `fk_ys_print_machine_ys_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_ys_print_machine_ys_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `yisong`.`ys_store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '打印机列表';


-- -----------------------------------------------------
-- Table `yisong`.`ys_user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_user_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(20) NOT NULL COMMENT '收货人姓名',
  `phone` VARCHAR(12) NOT NULL COMMENT '联系电话',
  `address` VARCHAR(100) NOT NULL COMMENT '收货地址',
  `location` VARCHAR(45) NOT NULL COMMENT '经纬度',
  `user_id` VARCHAR(30) NOT NULL,
  `is_default` INT NOT NULL DEFAULT 2 COMMENT '1：默认地址，2：普通地址',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC),
  INDEX `fk_ys_user_address_ys_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ys_user_address_ys_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yisong`.`ys_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户收货地址';


-- -----------------------------------------------------
-- Table `yisong`.`ys_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` VARCHAR(30) NOT NULL,
  `pay_type` INT NOT NULL COMMENT '1:线上付款，2：货到付款，3：钱包支付',
  `note` VARCHAR(255) NULL COMMENT '备注',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `price` DOUBLE(16,2) NOT NULL COMMENT '单价',
  `dicount` DOUBLE(16,2) NULL,
  `pay_price` DOUBLE(16,2) NOT NULL,
  `pay_status` INT NOT NULL DEFAULT 2 COMMENT '支付状态，1：已支付，2：未支付',
  `send` INT NOT NULL DEFAULT 1 COMMENT '发货状态,1:待确认，2:待发货，3：已发货，4：已退货',
  `address_id` VARCHAR(40) NOT NULL,
  `user_id` VARCHAR(40) NOT NULL,
  `store_id` VARCHAR(40) NOT NULL,
  `send_money` DOUBLE(16,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC),
  INDEX `fk_ys_order_ys_user_address1_idx` (`address_id` ASC),
  INDEX `fk_ys_order_ys_user1_idx` (`user_id` ASC),
  INDEX `fk_ys_order_ys_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_ys_order_ys_user_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `yisong`.`ys_user_address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ys_order_ys_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yisong`.`ys_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ys_order_ys_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `yisong`.`ys_store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '订单表';


-- -----------------------------------------------------
-- Table `yisong`.`ys_order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_order_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_item_id` VARCHAR(40) NOT NULL,
  `price` DOUBLE(16,2) NOT NULL,
  `discount` DOUBLE(16,2) NULL,
  `pay_price` DOUBLE(16,2) NOT NULL,
  `count` DOUBLE(16,2) NOT NULL,
  `order_id` VARCHAR(30) NOT NULL,
  `goods_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_item_id_UNIQUE` (`order_item_id` ASC),
  INDEX `fk_ys_order_item_ys_order1_idx` (`order_id` ASC),
  INDEX `fk_ys_order_item_ys_goods1_idx` (`goods_id` ASC),
  CONSTRAINT `fk_ys_order_item_ys_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `yisong`.`ys_order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ys_order_item_ys_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `yisong`.`ys_goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '订单商品b表';


-- -----------------------------------------------------
-- Table `yisong`.`ys_admin_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_admin_rule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rule_name` VARCHAR(45) NOT NULL,
  `rule_desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '权限规则';


-- -----------------------------------------------------
-- Table `yisong`.`ys_market_strategy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_market_strategy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `strategy_name` VARCHAR(45) NOT NULL,
  `strategy_desc` VARCHAR(100) NULL,
  `begin_time` TIMESTAMP NULL,
  `end_time` TIMESTAMP NULL,
  `user_level_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ys_market_strategy_ys_user_level1_idx` (`user_level_id` ASC),
  CONSTRAINT `fk_ys_market_strategy_ys_user_level1`
    FOREIGN KEY (`user_level_id`)
    REFERENCES `yisong`.`ys_user_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '营销策略';


-- -----------------------------------------------------
-- Table `yisong`.`ys_wallet_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yisong`.`ys_wallet_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `add_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `money` DOUBLE(16,2) NOT NULL,
  `user_id` VARCHAR(30) NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ys_wallet_log_ys_user1_idx` (`user_id` ASC),
  INDEX `fk_ys_wallet_log_ys_admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_ys_wallet_log_ys_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yisong`.`ys_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ys_wallet_log_ys_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `yisong`.`ys_admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
