spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/yisong?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
      username: root
      password: root


logging:
  level:
    root: error
    org.springframeword: info
    org.mybatis: error
    com.sumixer.ys: info
    me.chanjar.weixin: info

debug: false
