package com.sumixer.ys.api.dao;

import com.sumixer.ys.api.entity.YsGoodsDiscount;
import com.sumixer.ys.api.entity.YsGoodsDiscountExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface YsGoodsDiscountMapper {
    @SelectProvider(type=YsGoodsDiscountSqlProvider.class, method="countByExample")
    long countByExample(YsGoodsDiscountExample example);

    @DeleteProvider(type=YsGoodsDiscountSqlProvider.class, method="deleteByExample")
    int deleteByExample(YsGoodsDiscountExample example);

    @Delete({
        "delete from ys_goods_discount",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into ys_goods_discount (discount_id, goods_id, ",
        "discount, begin_time, ",
        "end_time)",
        "values (#{discountId,jdbcType=VARCHAR}, #{goodsId,jdbcType=VARCHAR}, ",
        "#{discount,jdbcType=DOUBLE}, #{beginTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(YsGoodsDiscount record);

    @InsertProvider(type=YsGoodsDiscountSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(YsGoodsDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_goods_discount
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsGoodsDiscount selectOneByExample(YsGoodsDiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_goods_discount
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsGoodsDiscount selectOneByExampleSelective(@Param("example") YsGoodsDiscountExample example, @Param("selective") YsGoodsDiscount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_goods_discount
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YsGoodsDiscount> selectByExampleSelective(@Param("example") YsGoodsDiscountExample example, @Param("selective") YsGoodsDiscount.Column ... selective);

    @SelectProvider(type=YsGoodsDiscountSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="discount_id", property="discountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="discount", property="discount", jdbcType=JdbcType.DOUBLE),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<YsGoodsDiscount> selectByExample(YsGoodsDiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_goods_discount
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsGoodsDiscount selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YsGoodsDiscount.Column ... selective);

    @Select({
        "select",
        "id, discount_id, goods_id, discount, begin_time, end_time",
        "from ys_goods_discount",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="discount_id", property="discountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="discount", property="discount", jdbcType=JdbcType.DOUBLE),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP)
    })
    YsGoodsDiscount selectByPrimaryKey(Integer id);

    @UpdateProvider(type=YsGoodsDiscountSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") YsGoodsDiscount record, @Param("example") YsGoodsDiscountExample example);

    @UpdateProvider(type=YsGoodsDiscountSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") YsGoodsDiscount record, @Param("example") YsGoodsDiscountExample example);

    @UpdateProvider(type=YsGoodsDiscountSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(YsGoodsDiscount record);

    @Update({
        "update ys_goods_discount",
        "set discount_id = #{discountId,jdbcType=VARCHAR},",
          "goods_id = #{goodsId,jdbcType=VARCHAR},",
          "discount = #{discount,jdbcType=DOUBLE},",
          "begin_time = #{beginTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(YsGoodsDiscount record);
}