package com.sumixer.ys.api.dao;

import com.sumixer.ys.api.entity.YsGoodsCategory;
import com.sumixer.ys.api.entity.YsGoodsCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface YsGoodsCategoryMapper {
    @SelectProvider(type=YsGoodsCategorySqlProvider.class, method="countByExample")
    long countByExample(YsGoodsCategoryExample example);

    @DeleteProvider(type=YsGoodsCategorySqlProvider.class, method="deleteByExample")
    int deleteByExample(YsGoodsCategoryExample example);

    @Delete({
        "delete from ys_goods_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into ys_goods_category (category_id, category_name, ",
        "parent_id, `rank`, ",
        "description, icon)",
        "values (#{categoryId,jdbcType=VARCHAR}, #{categoryName,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=VARCHAR}, #{rank,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{icon,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(YsGoodsCategory record);

    @InsertProvider(type=YsGoodsCategorySqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(YsGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_goods_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsGoodsCategory selectOneByExample(YsGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_goods_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsGoodsCategory selectOneByExampleSelective(@Param("example") YsGoodsCategoryExample example, @Param("selective") YsGoodsCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_goods_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YsGoodsCategory> selectByExampleSelective(@Param("example") YsGoodsCategoryExample example, @Param("selective") YsGoodsCategory.Column ... selective);

    @SelectProvider(type=YsGoodsCategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="rank", property="rank", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR)
    })
    List<YsGoodsCategory> selectByExample(YsGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_goods_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsGoodsCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YsGoodsCategory.Column ... selective);

    @Select({
        "select",
        "id, category_id, category_name, parent_id, `rank`, description, icon",
        "from ys_goods_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="rank", property="rank", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR)
    })
    YsGoodsCategory selectByPrimaryKey(Integer id);

    @UpdateProvider(type=YsGoodsCategorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") YsGoodsCategory record, @Param("example") YsGoodsCategoryExample example);

    @UpdateProvider(type=YsGoodsCategorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") YsGoodsCategory record, @Param("example") YsGoodsCategoryExample example);

    @UpdateProvider(type=YsGoodsCategorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(YsGoodsCategory record);

    @Update({
        "update ys_goods_category",
        "set category_id = #{categoryId,jdbcType=VARCHAR},",
          "category_name = #{categoryName,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=VARCHAR},",
          "`rank` = #{rank,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "icon = #{icon,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(YsGoodsCategory record);
}