package com.sumixer.ys.api.dao;

import com.sumixer.ys.api.entity.YsOrderItem;
import com.sumixer.ys.api.entity.YsOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface YsOrderItemMapper {
    @SelectProvider(type=YsOrderItemSqlProvider.class, method="countByExample")
    long countByExample(YsOrderItemExample example);

    @DeleteProvider(type=YsOrderItemSqlProvider.class, method="deleteByExample")
    int deleteByExample(YsOrderItemExample example);

    @Delete({
        "delete from ys_order_item",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into ys_order_item (order_item_id, price, ",
        "discount, pay_price, ",
        "`count`, order_id, goods_id)",
        "values (#{orderItemId,jdbcType=VARCHAR}, #{price,jdbcType=DOUBLE}, ",
        "#{discount,jdbcType=DOUBLE}, #{payPrice,jdbcType=DOUBLE}, ",
        "#{count,jdbcType=DOUBLE}, #{orderId,jdbcType=VARCHAR}, #{goodsId,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(YsOrderItem record);

    @InsertProvider(type=YsOrderItemSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(YsOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsOrderItem selectOneByExample(YsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsOrderItem selectOneByExampleSelective(@Param("example") YsOrderItemExample example, @Param("selective") YsOrderItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YsOrderItem> selectByExampleSelective(@Param("example") YsOrderItemExample example, @Param("selective") YsOrderItem.Column ... selective);

    @SelectProvider(type=YsOrderItemSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_item_id", property="orderItemId", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="discount", property="discount", jdbcType=JdbcType.DOUBLE),
        @Result(column="pay_price", property="payPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="count", property="count", jdbcType=JdbcType.DOUBLE),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_name", property="goodsName", jdbcType=JdbcType.VARCHAR)
    })
    List<YsOrderItem> selectByExample(YsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_order_item
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsOrderItem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YsOrderItem.Column ... selective);

    @Select({
        "select",
        "id, order_item_id, price, discount, pay_price, `count`, order_id, goods_id",
        "from ys_order_item",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_item_id", property="orderItemId", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="discount", property="discount", jdbcType=JdbcType.DOUBLE),
        @Result(column="pay_price", property="payPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="count", property="count", jdbcType=JdbcType.DOUBLE),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR)
    })
    YsOrderItem selectByPrimaryKey(Integer id);

    @UpdateProvider(type=YsOrderItemSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") YsOrderItem record, @Param("example") YsOrderItemExample example);

    @UpdateProvider(type=YsOrderItemSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") YsOrderItem record, @Param("example") YsOrderItemExample example);

    @UpdateProvider(type=YsOrderItemSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(YsOrderItem record);

    @Update({
        "update ys_order_item",
        "set order_item_id = #{orderItemId,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DOUBLE},",
          "discount = #{discount,jdbcType=DOUBLE},",
          "pay_price = #{payPrice,jdbcType=DOUBLE},",
          "`count` = #{count,jdbcType=DOUBLE},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "goods_id = #{goodsId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(YsOrderItem record);

    @InsertProvider(type = YsOrderItemSqlProvider.class, method = "insertList")
    int insertList(@Param("list") List<YsOrderItem> items);
}