package com.sumixer.ys.api.dao;

import com.sumixer.ys.api.entity.YsStoreMenu;
import com.sumixer.ys.api.entity.YsStoreMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface YsStoreMenuMapper {
    @SelectProvider(type=YsStoreMenuSqlProvider.class, method="countByExample")
    long countByExample(YsStoreMenuExample example);

    @DeleteProvider(type=YsStoreMenuSqlProvider.class, method="deleteByExample")
    int deleteByExample(YsStoreMenuExample example);

    @Delete({
        "delete from ys_store_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into ys_store_menu (menu_id, menu_name, ",
        "update_time, store_id, ",
        "goods_id)",
        "values (#{menuId,jdbcType=VARCHAR}, #{menuName,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{storeId,jdbcType=VARCHAR}, ",
        "#{goodsId,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(YsStoreMenu record);

    @InsertProvider(type=YsStoreMenuSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(YsStoreMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsStoreMenu selectOneByExample(YsStoreMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsStoreMenu selectOneByExampleSelective(@Param("example") YsStoreMenuExample example, @Param("selective") YsStoreMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YsStoreMenu> selectByExampleSelective(@Param("example") YsStoreMenuExample example, @Param("selective") YsStoreMenu.Column ... selective);

    @SelectProvider(type=YsStoreMenuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="menu_id", property="menuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="menu_name", property="menuName", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR)
    })
    List<YsStoreMenu> selectByExample(YsStoreMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsStoreMenu selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YsStoreMenu.Column ... selective);

    @Select({
        "select",
        "id, menu_id, menu_name, update_time, store_id, goods_id",
        "from ys_store_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="menu_id", property="menuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="menu_name", property="menuName", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR)
    })
    YsStoreMenu selectByPrimaryKey(Integer id);

    @UpdateProvider(type=YsStoreMenuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") YsStoreMenu record, @Param("example") YsStoreMenuExample example);

    @UpdateProvider(type=YsStoreMenuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") YsStoreMenu record, @Param("example") YsStoreMenuExample example);

    @UpdateProvider(type=YsStoreMenuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(YsStoreMenu record);

    @Update({
        "update ys_store_menu",
        "set menu_id = #{menuId,jdbcType=VARCHAR},",
          "menu_name = #{menuName,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "store_id = #{storeId,jdbcType=VARCHAR},",
          "goods_id = #{goodsId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(YsStoreMenu record);
}