package com.sumixer.ys.api.dao;

import com.sumixer.ys.api.entity.YsStore;
import com.sumixer.ys.api.entity.YsStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface YsStoreMapper {
    @SelectProvider(type=YsStoreSqlProvider.class, method="countByExample")
    long countByExample(YsStoreExample example);

    @DeleteProvider(type=YsStoreSqlProvider.class, method="deleteByExample")
    int deleteByExample(YsStoreExample example);

    @Delete({
        "delete from ys_store",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into ys_store (store_id, agent_id, ",
        "store_name, localtion, ",
        "`path`, `status`, create_time, ",
        "begin_time, end_time, ",
        "contact_name, contact_phone, ",
        "address, area, business_lice, ",
        "idcard_up, idcard_down, ",
        "send_money, open_day, ",
        "open_begin_time, open_end_time)",
        "values (#{storeId,jdbcType=VARCHAR}, #{agentId,jdbcType=VARCHAR}, ",
        "#{storeName,jdbcType=VARCHAR}, #{localtion,jdbcType=VARCHAR}, ",
        "#{path,jdbcType=DOUBLE}, #{status,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{beginTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{contactName,jdbcType=VARCHAR}, #{contactPhone,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{area,jdbcType=VARCHAR}, #{businessLice,jdbcType=VARCHAR}, ",
        "#{idcardUp,jdbcType=VARCHAR}, #{idcardDown,jdbcType=VARCHAR}, ",
        "#{sendMoney,jdbcType=DOUBLE}, #{openDay,jdbcType=VARCHAR}, ",
        "#{openBeginTime,jdbcType=INTEGER}, #{openEndTime,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(YsStore record);

    @InsertProvider(type=YsStoreSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(YsStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsStore selectOneByExample(YsStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsStore selectOneByExampleSelective(@Param("example") YsStoreExample example, @Param("selective") YsStore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YsStore> selectByExampleSelective(@Param("example") YsStoreExample example, @Param("selective") YsStore.Column ... selective);

    @SelectProvider(type=YsStoreSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent_id", property="agentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="store_name", property="storeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="localtion", property="localtion", jdbcType=JdbcType.VARCHAR),
        @Result(column="path", property="path", jdbcType=JdbcType.DOUBLE),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="contact_name", property="contactName", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact_phone", property="contactPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="area", property="area", jdbcType=JdbcType.VARCHAR),
        @Result(column="business_lice", property="businessLice", jdbcType=JdbcType.VARCHAR),
        @Result(column="idcard_up", property="idcardUp", jdbcType=JdbcType.VARCHAR),
        @Result(column="idcard_down", property="idcardDown", jdbcType=JdbcType.VARCHAR),
        @Result(column="send_money", property="sendMoney", jdbcType=JdbcType.DOUBLE),
        @Result(column="open_day", property="openDay", jdbcType=JdbcType.VARCHAR),
        @Result(column="open_begin_time", property="openBeginTime", jdbcType=JdbcType.INTEGER),
        @Result(column="open_end_time", property="openEndTime", jdbcType=JdbcType.INTEGER)
    })
    List<YsStore> selectByExample(YsStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsStore selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YsStore.Column ... selective);

    @Select({
        "select",
        "id, store_id, agent_id, store_name, localtion, `path`, `status`, create_time, ",
        "begin_time, end_time, contact_name, contact_phone, address, area, business_lice, ",
        "idcard_up, idcard_down, send_money, open_day, open_begin_time, open_end_time",
        "from ys_store",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="agent_id", property="agentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="store_name", property="storeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="localtion", property="localtion", jdbcType=JdbcType.VARCHAR),
        @Result(column="path", property="path", jdbcType=JdbcType.DOUBLE),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="contact_name", property="contactName", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact_phone", property="contactPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="area", property="area", jdbcType=JdbcType.VARCHAR),
        @Result(column="business_lice", property="businessLice", jdbcType=JdbcType.VARCHAR),
        @Result(column="idcard_up", property="idcardUp", jdbcType=JdbcType.VARCHAR),
        @Result(column="idcard_down", property="idcardDown", jdbcType=JdbcType.VARCHAR),
        @Result(column="send_money", property="sendMoney", jdbcType=JdbcType.DOUBLE),
        @Result(column="open_day", property="openDay", jdbcType=JdbcType.VARCHAR),
        @Result(column="open_begin_time", property="openBeginTime", jdbcType=JdbcType.INTEGER),
        @Result(column="open_end_time", property="openEndTime", jdbcType=JdbcType.INTEGER)
    })
    YsStore selectByPrimaryKey(Integer id);

    @UpdateProvider(type=YsStoreSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") YsStore record, @Param("example") YsStoreExample example);

    @UpdateProvider(type=YsStoreSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") YsStore record, @Param("example") YsStoreExample example);

    @UpdateProvider(type=YsStoreSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(YsStore record);

    @Update({
        "update ys_store",
        "set store_id = #{storeId,jdbcType=VARCHAR},",
          "agent_id = #{agentId,jdbcType=VARCHAR},",
          "store_name = #{storeName,jdbcType=VARCHAR},",
          "localtion = #{localtion,jdbcType=VARCHAR},",
          "`path` = #{path,jdbcType=DOUBLE},",
          "`status` = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "begin_time = #{beginTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "contact_name = #{contactName,jdbcType=VARCHAR},",
          "contact_phone = #{contactPhone,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "area = #{area,jdbcType=VARCHAR},",
          "business_lice = #{businessLice,jdbcType=VARCHAR},",
          "idcard_up = #{idcardUp,jdbcType=VARCHAR},",
          "idcard_down = #{idcardDown,jdbcType=VARCHAR},",
          "send_money = #{sendMoney,jdbcType=DOUBLE},",
          "open_day = #{openDay,jdbcType=VARCHAR},",
          "open_begin_time = #{openBeginTime,jdbcType=INTEGER},",
          "open_end_time = #{openEndTime,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(YsStore record);
}