package com.sumixer.ys.api.dao;

import com.sumixer.ys.api.entity.YsStoreCloseTime;
import com.sumixer.ys.api.entity.YsStoreCloseTimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface YsStoreCloseTimeMapper {
    @SelectProvider(type=YsStoreCloseTimeSqlProvider.class, method="countByExample")
    long countByExample(YsStoreCloseTimeExample example);

    @DeleteProvider(type=YsStoreCloseTimeSqlProvider.class, method="deleteByExample")
    int deleteByExample(YsStoreCloseTimeExample example);

    @Delete({
        "delete from ys_store_close_time",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into ys_store_close_time (begin_time, end_time, ",
        "store_id)",
        "values (#{beginTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{storeId,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(YsStoreCloseTime record);

    @InsertProvider(type=YsStoreCloseTimeSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(YsStoreCloseTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store_close_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsStoreCloseTime selectOneByExample(YsStoreCloseTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store_close_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsStoreCloseTime selectOneByExampleSelective(@Param("example") YsStoreCloseTimeExample example, @Param("selective") YsStoreCloseTime.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store_close_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YsStoreCloseTime> selectByExampleSelective(@Param("example") YsStoreCloseTimeExample example, @Param("selective") YsStoreCloseTime.Column ... selective);

    @SelectProvider(type=YsStoreCloseTimeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.VARCHAR)
    })
    List<YsStoreCloseTime> selectByExample(YsStoreCloseTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store_close_time
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsStoreCloseTime selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YsStoreCloseTime.Column ... selective);

    @Select({
        "select",
        "id, begin_time, end_time, store_id",
        "from ys_store_close_time",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.VARCHAR)
    })
    YsStoreCloseTime selectByPrimaryKey(Integer id);

    @UpdateProvider(type=YsStoreCloseTimeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") YsStoreCloseTime record, @Param("example") YsStoreCloseTimeExample example);

    @UpdateProvider(type=YsStoreCloseTimeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") YsStoreCloseTime record, @Param("example") YsStoreCloseTimeExample example);

    @UpdateProvider(type=YsStoreCloseTimeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(YsStoreCloseTime record);

    @Update({
        "update ys_store_close_time",
        "set begin_time = #{beginTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "store_id = #{storeId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(YsStoreCloseTime record);
}