package com.sumixer.ys.api.dao;

import com.sumixer.ys.api.entity.YsWxUser;
import com.sumixer.ys.api.entity.YsWxUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface YsWxUserMapper {
    @SelectProvider(type=YsWxUserSqlProvider.class, method="countByExample")
    long countByExample(YsWxUserExample example);

    @DeleteProvider(type=YsWxUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(YsWxUserExample example);

    @Delete({
        "delete from ys_wx_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into ys_wx_user (openid, nickname, ",
        "sex, `language`, city, ",
        "province, country, ",
        "headimgurl, unionid, ",
        "wx_appid)",
        "values (#{openid,jdbcType=VARCHAR}, #{nickname,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=INTEGER}, #{language,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{province,jdbcType=VARCHAR}, #{country,jdbcType=VARCHAR}, ",
        "#{headimgurl,jdbcType=VARCHAR}, #{unionid,jdbcType=VARCHAR}, ",
        "#{wxAppid,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(YsWxUser record);

    @InsertProvider(type=YsWxUserSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(YsWxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_wx_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsWxUser selectOneByExample(YsWxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_wx_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsWxUser selectOneByExampleSelective(@Param("example") YsWxUserExample example, @Param("selective") YsWxUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_wx_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YsWxUser> selectByExampleSelective(@Param("example") YsWxUserExample example, @Param("selective") YsWxUser.Column ... selective);

    @SelectProvider(type=YsWxUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.INTEGER),
        @Result(column="language", property="language", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="headimgurl", property="headimgurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="unionid", property="unionid", jdbcType=JdbcType.VARCHAR),
        @Result(column="wx_appid", property="wxAppid", jdbcType=JdbcType.VARCHAR)
    })
    List<YsWxUser> selectByExample(YsWxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_wx_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YsWxUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") YsWxUser.Column ... selective);

    @Select({
        "select",
        "id, openid, nickname, sex, `language`, city, province, country, headimgurl, ",
        "unionid, wx_appid",
        "from ys_wx_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.INTEGER),
        @Result(column="language", property="language", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="headimgurl", property="headimgurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="unionid", property="unionid", jdbcType=JdbcType.VARCHAR),
        @Result(column="wx_appid", property="wxAppid", jdbcType=JdbcType.VARCHAR)
    })
    YsWxUser selectByPrimaryKey(Integer id);

    @UpdateProvider(type=YsWxUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") YsWxUser record, @Param("example") YsWxUserExample example);

    @UpdateProvider(type=YsWxUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") YsWxUser record, @Param("example") YsWxUserExample example);

    @UpdateProvider(type=YsWxUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(YsWxUser record);

    @Update({
        "update ys_wx_user",
        "set openid = #{openid,jdbcType=VARCHAR},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "`language` = #{language,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "province = #{province,jdbcType=VARCHAR},",
          "country = #{country,jdbcType=VARCHAR},",
          "headimgurl = #{headimgurl,jdbcType=VARCHAR},",
          "unionid = #{unionid,jdbcType=VARCHAR},",
          "wx_appid = #{wxAppid,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(YsWxUser record);
}