package com.sumixer.ys.api.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class YsStoreExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public YsStoreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public YsStoreExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ys_store
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public YsStoreExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("store_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("store_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(String value) {
            addCriterion("store_id =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(String value) {
            addCriterion("store_id <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(String value) {
            addCriterion("store_id >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(String value) {
            addCriterion("store_id >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(String value) {
            addCriterion("store_id <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(String value) {
            addCriterion("store_id <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLike(String value) {
            addCriterion("store_id like", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotLike(String value) {
            addCriterion("store_id not like", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<String> values) {
            addCriterion("store_id in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<String> values) {
            addCriterion("store_id not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(String value1, String value2) {
            addCriterion("store_id between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(String value1, String value2) {
            addCriterion("store_id not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andAgentIdIsNull() {
            addCriterion("agent_id is null");
            return (Criteria) this;
        }

        public Criteria andAgentIdIsNotNull() {
            addCriterion("agent_id is not null");
            return (Criteria) this;
        }

        public Criteria andAgentIdEqualTo(String value) {
            addCriterion("agent_id =", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotEqualTo(String value) {
            addCriterion("agent_id <>", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdGreaterThan(String value) {
            addCriterion("agent_id >", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdGreaterThanOrEqualTo(String value) {
            addCriterion("agent_id >=", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLessThan(String value) {
            addCriterion("agent_id <", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLessThanOrEqualTo(String value) {
            addCriterion("agent_id <=", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLike(String value) {
            addCriterion("agent_id like", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotLike(String value) {
            addCriterion("agent_id not like", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdIn(List<String> values) {
            addCriterion("agent_id in", values, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotIn(List<String> values) {
            addCriterion("agent_id not in", values, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdBetween(String value1, String value2) {
            addCriterion("agent_id between", value1, value2, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotBetween(String value1, String value2) {
            addCriterion("agent_id not between", value1, value2, "agentId");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNull() {
            addCriterion("store_name is null");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNotNull() {
            addCriterion("store_name is not null");
            return (Criteria) this;
        }

        public Criteria andStoreNameEqualTo(String value) {
            addCriterion("store_name =", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotEqualTo(String value) {
            addCriterion("store_name <>", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThan(String value) {
            addCriterion("store_name >", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThanOrEqualTo(String value) {
            addCriterion("store_name >=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThan(String value) {
            addCriterion("store_name <", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThanOrEqualTo(String value) {
            addCriterion("store_name <=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLike(String value) {
            addCriterion("store_name like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotLike(String value) {
            addCriterion("store_name not like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameIn(List<String> values) {
            addCriterion("store_name in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotIn(List<String> values) {
            addCriterion("store_name not in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameBetween(String value1, String value2) {
            addCriterion("store_name between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotBetween(String value1, String value2) {
            addCriterion("store_name not between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andLocaltionIsNull() {
            addCriterion("localtion is null");
            return (Criteria) this;
        }

        public Criteria andLocaltionIsNotNull() {
            addCriterion("localtion is not null");
            return (Criteria) this;
        }

        public Criteria andLocaltionEqualTo(String value) {
            addCriterion("localtion =", value, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionNotEqualTo(String value) {
            addCriterion("localtion <>", value, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionGreaterThan(String value) {
            addCriterion("localtion >", value, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionGreaterThanOrEqualTo(String value) {
            addCriterion("localtion >=", value, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionLessThan(String value) {
            addCriterion("localtion <", value, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionLessThanOrEqualTo(String value) {
            addCriterion("localtion <=", value, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionLike(String value) {
            addCriterion("localtion like", value, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionNotLike(String value) {
            addCriterion("localtion not like", value, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionIn(List<String> values) {
            addCriterion("localtion in", values, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionNotIn(List<String> values) {
            addCriterion("localtion not in", values, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionBetween(String value1, String value2) {
            addCriterion("localtion between", value1, value2, "localtion");
            return (Criteria) this;
        }

        public Criteria andLocaltionNotBetween(String value1, String value2) {
            addCriterion("localtion not between", value1, value2, "localtion");
            return (Criteria) this;
        }

        public Criteria andPathIsNull() {
            addCriterion("`path` is null");
            return (Criteria) this;
        }

        public Criteria andPathIsNotNull() {
            addCriterion("`path` is not null");
            return (Criteria) this;
        }

        public Criteria andPathEqualTo(Double value) {
            addCriterion("`path` =", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotEqualTo(Double value) {
            addCriterion("`path` <>", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThan(Double value) {
            addCriterion("`path` >", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThanOrEqualTo(Double value) {
            addCriterion("`path` >=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThan(Double value) {
            addCriterion("`path` <", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThanOrEqualTo(Double value) {
            addCriterion("`path` <=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathIn(List<Double> values) {
            addCriterion("`path` in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotIn(List<Double> values) {
            addCriterion("`path` not in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathBetween(Double value1, Double value2) {
            addCriterion("`path` between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotBetween(Double value1, Double value2) {
            addCriterion("`path` not between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("begin_time =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("begin_time <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("begin_time >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_time >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("begin_time <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("begin_time <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("begin_time in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("begin_time not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("begin_time between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("begin_time not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andContactNameIsNull() {
            addCriterion("contact_name is null");
            return (Criteria) this;
        }

        public Criteria andContactNameIsNotNull() {
            addCriterion("contact_name is not null");
            return (Criteria) this;
        }

        public Criteria andContactNameEqualTo(String value) {
            addCriterion("contact_name =", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotEqualTo(String value) {
            addCriterion("contact_name <>", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameGreaterThan(String value) {
            addCriterion("contact_name >", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameGreaterThanOrEqualTo(String value) {
            addCriterion("contact_name >=", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLessThan(String value) {
            addCriterion("contact_name <", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLessThanOrEqualTo(String value) {
            addCriterion("contact_name <=", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLike(String value) {
            addCriterion("contact_name like", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotLike(String value) {
            addCriterion("contact_name not like", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameIn(List<String> values) {
            addCriterion("contact_name in", values, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotIn(List<String> values) {
            addCriterion("contact_name not in", values, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameBetween(String value1, String value2) {
            addCriterion("contact_name between", value1, value2, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotBetween(String value1, String value2) {
            addCriterion("contact_name not between", value1, value2, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNull() {
            addCriterion("contact_phone is null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNotNull() {
            addCriterion("contact_phone is not null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneEqualTo(String value) {
            addCriterion("contact_phone =", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotEqualTo(String value) {
            addCriterion("contact_phone <>", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThan(String value) {
            addCriterion("contact_phone >", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("contact_phone >=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThan(String value) {
            addCriterion("contact_phone <", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("contact_phone <=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLike(String value) {
            addCriterion("contact_phone like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotLike(String value) {
            addCriterion("contact_phone not like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIn(List<String> values) {
            addCriterion("contact_phone in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotIn(List<String> values) {
            addCriterion("contact_phone not in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneBetween(String value1, String value2) {
            addCriterion("contact_phone between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotBetween(String value1, String value2) {
            addCriterion("contact_phone not between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceIsNull() {
            addCriterion("business_lice is null");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceIsNotNull() {
            addCriterion("business_lice is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceEqualTo(String value) {
            addCriterion("business_lice =", value, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceNotEqualTo(String value) {
            addCriterion("business_lice <>", value, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceGreaterThan(String value) {
            addCriterion("business_lice >", value, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceGreaterThanOrEqualTo(String value) {
            addCriterion("business_lice >=", value, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceLessThan(String value) {
            addCriterion("business_lice <", value, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceLessThanOrEqualTo(String value) {
            addCriterion("business_lice <=", value, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceLike(String value) {
            addCriterion("business_lice like", value, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceNotLike(String value) {
            addCriterion("business_lice not like", value, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceIn(List<String> values) {
            addCriterion("business_lice in", values, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceNotIn(List<String> values) {
            addCriterion("business_lice not in", values, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceBetween(String value1, String value2) {
            addCriterion("business_lice between", value1, value2, "businessLice");
            return (Criteria) this;
        }

        public Criteria andBusinessLiceNotBetween(String value1, String value2) {
            addCriterion("business_lice not between", value1, value2, "businessLice");
            return (Criteria) this;
        }

        public Criteria andIdcardUpIsNull() {
            addCriterion("idcard_up is null");
            return (Criteria) this;
        }

        public Criteria andIdcardUpIsNotNull() {
            addCriterion("idcard_up is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardUpEqualTo(String value) {
            addCriterion("idcard_up =", value, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpNotEqualTo(String value) {
            addCriterion("idcard_up <>", value, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpGreaterThan(String value) {
            addCriterion("idcard_up >", value, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpGreaterThanOrEqualTo(String value) {
            addCriterion("idcard_up >=", value, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpLessThan(String value) {
            addCriterion("idcard_up <", value, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpLessThanOrEqualTo(String value) {
            addCriterion("idcard_up <=", value, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpLike(String value) {
            addCriterion("idcard_up like", value, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpNotLike(String value) {
            addCriterion("idcard_up not like", value, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpIn(List<String> values) {
            addCriterion("idcard_up in", values, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpNotIn(List<String> values) {
            addCriterion("idcard_up not in", values, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpBetween(String value1, String value2) {
            addCriterion("idcard_up between", value1, value2, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardUpNotBetween(String value1, String value2) {
            addCriterion("idcard_up not between", value1, value2, "idcardUp");
            return (Criteria) this;
        }

        public Criteria andIdcardDownIsNull() {
            addCriterion("idcard_down is null");
            return (Criteria) this;
        }

        public Criteria andIdcardDownIsNotNull() {
            addCriterion("idcard_down is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardDownEqualTo(String value) {
            addCriterion("idcard_down =", value, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownNotEqualTo(String value) {
            addCriterion("idcard_down <>", value, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownGreaterThan(String value) {
            addCriterion("idcard_down >", value, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownGreaterThanOrEqualTo(String value) {
            addCriterion("idcard_down >=", value, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownLessThan(String value) {
            addCriterion("idcard_down <", value, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownLessThanOrEqualTo(String value) {
            addCriterion("idcard_down <=", value, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownLike(String value) {
            addCriterion("idcard_down like", value, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownNotLike(String value) {
            addCriterion("idcard_down not like", value, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownIn(List<String> values) {
            addCriterion("idcard_down in", values, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownNotIn(List<String> values) {
            addCriterion("idcard_down not in", values, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownBetween(String value1, String value2) {
            addCriterion("idcard_down between", value1, value2, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andIdcardDownNotBetween(String value1, String value2) {
            addCriterion("idcard_down not between", value1, value2, "idcardDown");
            return (Criteria) this;
        }

        public Criteria andSendMoneyIsNull() {
            addCriterion("send_money is null");
            return (Criteria) this;
        }

        public Criteria andSendMoneyIsNotNull() {
            addCriterion("send_money is not null");
            return (Criteria) this;
        }

        public Criteria andSendMoneyEqualTo(Double value) {
            addCriterion("send_money =", value, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andSendMoneyNotEqualTo(Double value) {
            addCriterion("send_money <>", value, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andSendMoneyGreaterThan(Double value) {
            addCriterion("send_money >", value, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andSendMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("send_money >=", value, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andSendMoneyLessThan(Double value) {
            addCriterion("send_money <", value, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andSendMoneyLessThanOrEqualTo(Double value) {
            addCriterion("send_money <=", value, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andSendMoneyIn(List<Double> values) {
            addCriterion("send_money in", values, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andSendMoneyNotIn(List<Double> values) {
            addCriterion("send_money not in", values, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andSendMoneyBetween(Double value1, Double value2) {
            addCriterion("send_money between", value1, value2, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andSendMoneyNotBetween(Double value1, Double value2) {
            addCriterion("send_money not between", value1, value2, "sendMoney");
            return (Criteria) this;
        }

        public Criteria andOpenDayIsNull() {
            addCriterion("open_day is null");
            return (Criteria) this;
        }

        public Criteria andOpenDayIsNotNull() {
            addCriterion("open_day is not null");
            return (Criteria) this;
        }

        public Criteria andOpenDayEqualTo(String value) {
            addCriterion("open_day =", value, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayNotEqualTo(String value) {
            addCriterion("open_day <>", value, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayGreaterThan(String value) {
            addCriterion("open_day >", value, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayGreaterThanOrEqualTo(String value) {
            addCriterion("open_day >=", value, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayLessThan(String value) {
            addCriterion("open_day <", value, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayLessThanOrEqualTo(String value) {
            addCriterion("open_day <=", value, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayLike(String value) {
            addCriterion("open_day like", value, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayNotLike(String value) {
            addCriterion("open_day not like", value, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayIn(List<String> values) {
            addCriterion("open_day in", values, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayNotIn(List<String> values) {
            addCriterion("open_day not in", values, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayBetween(String value1, String value2) {
            addCriterion("open_day between", value1, value2, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenDayNotBetween(String value1, String value2) {
            addCriterion("open_day not between", value1, value2, "openDay");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeIsNull() {
            addCriterion("open_begin_time is null");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeIsNotNull() {
            addCriterion("open_begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeEqualTo(Integer value) {
            addCriterion("open_begin_time =", value, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeNotEqualTo(Integer value) {
            addCriterion("open_begin_time <>", value, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeGreaterThan(Integer value) {
            addCriterion("open_begin_time >", value, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("open_begin_time >=", value, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeLessThan(Integer value) {
            addCriterion("open_begin_time <", value, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeLessThanOrEqualTo(Integer value) {
            addCriterion("open_begin_time <=", value, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeIn(List<Integer> values) {
            addCriterion("open_begin_time in", values, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeNotIn(List<Integer> values) {
            addCriterion("open_begin_time not in", values, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeBetween(Integer value1, Integer value2) {
            addCriterion("open_begin_time between", value1, value2, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenBeginTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("open_begin_time not between", value1, value2, "openBeginTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeIsNull() {
            addCriterion("open_end_time is null");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeIsNotNull() {
            addCriterion("open_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeEqualTo(Integer value) {
            addCriterion("open_end_time =", value, "openEndTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeNotEqualTo(Integer value) {
            addCriterion("open_end_time <>", value, "openEndTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeGreaterThan(Integer value) {
            addCriterion("open_end_time >", value, "openEndTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("open_end_time >=", value, "openEndTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeLessThan(Integer value) {
            addCriterion("open_end_time <", value, "openEndTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeLessThanOrEqualTo(Integer value) {
            addCriterion("open_end_time <=", value, "openEndTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeIn(List<Integer> values) {
            addCriterion("open_end_time in", values, "openEndTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeNotIn(List<Integer> values) {
            addCriterion("open_end_time not in", values, "openEndTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeBetween(Integer value1, Integer value2) {
            addCriterion("open_end_time between", value1, value2, "openEndTime");
            return (Criteria) this;
        }

        public Criteria andOpenEndTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("open_end_time not between", value1, value2, "openEndTime");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ys_store
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private YsStoreExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ys_store
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(YsStoreExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ys_store
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public YsStoreExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ys_store
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table ys_store
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table ys_store
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}